### ISSUE TITLE
Diablo IV - Live split does not recognize other categories than full game

### ISSUE THREAD

**Issue by M1PY** [LiveSplit/LiveSplit#2359] opened 2023-08-25 18:25 UTC
Hello, I am M1PY and I am co-moderating Diablo IV on speedrun.com.

We created new sub-categories under the "levels" category for Diablo IV for Nightmare Dungeon Speedrunning.

However, these are not recognized by Livesplit. If we add a new category to "full game", Livesplit recognizes it immediately. Is there a way to make livesplit recognize the "levels" category and it's sub-categories?

Best regards
M1PY

**Comment by LukeSaward1** [comment] 2023-10-19 22:55
Are the categories under the individual levels section in SRC?
If so, LiveSplit does not support this.

**Comment by wooferzfg** [comment] 2024-04-23 04:04
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/2075

**Closed by wooferzfg** 2024-04-23 04:04 UTC
