### ISSUE TITLE
[Feature request] Save paused timer and continue later

### ISSUE THREAD

**Issue by daanbom** [LiveSplit/LiveSplit#2197] opened 2021-12-15 01:21 UTC
Hey, I am a streamer and I often do fun challenges for games like Dark souls. Here is use livesplit over multiple  streams and I would like to use splits and keep the timer when I start playing the next day. Can u guys make a function like this for me that would be greatly appreciated

**Comment by TheBoxyBear** [comment] 2021-12-18 17:33
I wanted the same feature so looking into implementing it myself. Not sure if I can match the standards to be merge into master however.

**Comment by amcknight** [comment] 2022-04-15 05:06
Did you have any luck with this @TheBoxyBear ?

**Comment by TheBoxyBear** [comment] 2022-04-17 02:58
> Did you have any luck with this @TheBoxyBear ?

Unfortunately, no. I can't even get master to compile.

**Comment by Shotnex4** [comment] 2024-01-28 15:26
Hey everyone, I also missed this feature.
I developed a LiveSplit Component which you can use to save your progress mid run to a file. With that you can close LiveSplit and even shutdown your PC. Just import the file when you are back and you can continue:
https://github.com/Shotnex4/LiveSplit.TimeAttackPause

**Comment by just-ero** [comment] 2024-04-19 09:15
Closing as duplicate of #952.

**Closed by just-ero** 2024-04-19 09:15 UTC
Labels: duplicate
