### ISSUE TITLE
LiveSplit 1.6.9 takes over a minute (!) to start

### ISSUE THREAD

**Issue by Zamiell** [LiveSplit/LiveSplit#640] opened 2016-11-04 18:20 UTC
On Windows 7 Professional, the time differential between when LiveSplit.exe is executed to the time that the actual window is drawn is a variable length amount of time. In the longest cases, it can take over a minute or longer.

After an extremely long start time, if I immediately close it and start it again, then it takes less than a second to start (which is probably the normal/expected behavior). But if I close it, wait 10 minutes, then start it again, then I get the long start time.

It almost seems like LiveSplit is attempting to check for updates and then timing out or some such.

Is there a log file generated somewhere that I can post?

**Comment by wooferzfg** [comment] 2016-11-26 04:22
http://pastebin.com/M3n52ABV

**Comment by Zamiell** [comment] 2017-04-09 17:58
Can you add that information to the README.md file?

**Comment by zamora** [comment] 2017-08-23 00:37
I may be seeing this same problem with 1.7.4  For me, the issue is that I have a NAS device, and LiveSplit seems to try to access it. If the NAS is in sleep mode, LiveSplit hangs until the NAS comes out of sleep mode and is active. If the NAS is active, then LiveSplit starts quickly. I'm not sure why LiveSplit would be checking the NAS. The NAS is not mapped as a drive, and I don't have any system files on it.

**Comment by wooferzfg** [comment] 2020-04-22 06:43
This should be resolved in LiveSplit 1.8.

**Closed by wooferzfg** 2020-04-22 06:43 UTC
Labels: Needs assistance
