### ISSUE TITLE
Not DPI aware

### ISSUE THREAD

**Issue by heavyutils** [LiveSplit/LiveSplit#2346] opened 2023-07-25 10:53 UTC
The LiveSplit looks blurry and oversized on displays with different scaling. I do know the fix, though. It has also been tested to successfully work on an otherwise unedited clone of LiveSplit.
In Program.cs:
```
static void Main(string[] args)
        {
            try
            {
                // Add this:
                if (Environment.OSVersion.Version.Major >= 6)
                    SetProcessDPIAware();

                // The rest of the code is omitted to not make it a mess
            }
            finally
            {
                // There's no code in 'finally'
            }
      }
// And this:
[System.Runtime.InteropServices.DllImport("user32.dll")]
private static extern bool SetProcessDPIAware();
```
This obviously isn't the complete Program.cs; it only shows what to add where.
It fixes the blurriness and that it's oversized in different scalings.

**Comment by just-ero** [comment] 2024-04-18 09:26
Duplicate of #2336, as mentioned there. This issue contains a potential fix.

Close as you see fit @wooferzfg.

**Closed** 2024-04-18 12:46 UTC
Labels: Duplicate
