### ISSUE TITLE
Timing Method Overrides

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#689] opened 2017-01-28 15:01 UTC
[RastaBobby_](https://twitter.com/RastaBobby_/status/825357092492029954) wants this for Trackmania Turbo.

**Comment by wooferzfg** [comment] 2017-08-29 01:03
the World Record Component should have this

**Comment by wooferzfg** [comment] 2024-04-23 03:02
Duplicate of #2474

**Closed by wooferzfg** 2024-04-23 03:02 UTC
Labels: enhancement
