### ISSUE TITLE
Issue with setting spit controls 

### ISSUE THREAD

**Issue by Toaster6746** [LiveSplit/LiveSplit#1977] opened 2020-07-31 12:42 UTC
I'm having an issue with setting my controls on livesplit to the mouse 4+5

**Comment by Skyteus01** [comment] 2020-08-02 10:36
Same here, my Mouse buttons 4 and 5 always worked before but know I can't even bind them to start and reset.

**Comment by wooferzfg** [comment] 2020-08-11 07:33
Can you try this? https://github.com/LiveSplit/LiveSplit/issues/1980#issuecomment-667455423

**Comment by BoraxKid** [comment] 2022-05-28 10:38
For anyone with this issue, the solution in #1980 worked, but not directly. 

With the Settings window open, Enable "Allow Gamepads as Hotkeys", than press OK to close the window, only then you can re-open the Settings window and it will allow you to use mouse button.

Atleast in my case I had to do this, it didn't register the side mouse buttons without first closing the Settings window

**Comment by just-ero** [comment] 2024-04-19 09:37
Closing as duplicate of #1980.

**Closed** 2024-04-19 09:37 UTC
Labels: duplicate

**Comment by just-ero** [comment] 2024-04-19 09:48
The issue appears to have been resolved.
