### ISSUE TITLE
Random Crashes when clicking on livesplit or attempting to save/close splits

### ISSUE THREAD

**Issue by arengarajan99** [LiveSplit/LiveSplit#1889] opened 2020-06-15 06:31 UTC
Error Logs From Event Viewer in Windows:

```
HRESULT: [0x8007001E], Module: [SharpDX.DirectInput], ApiCode: [DIERR_INPUTLOST/InputLost], Message: The system cannot read from the specified device.
   at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.Device.GetDeviceData(Int32 arg0, IntPtr arg1, Int32& arg2, Int32 arg3)
   at SharpDX.DirectInput.CustomDevice`3.GetBufferedData()
   at LiveSplit.Model.Input.GamepadHook.Poll()
```

```
Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)
```

```
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at LiveSplit.View.TimerForm.WndProc(Message& m)
```

**Comment by wooferzfg** [comment] 2020-06-15 06:37
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/1867

**Closed by wooferzfg** 2020-06-15 06:37 UTC

**Comment by wooferzfg** [comment] 2020-06-15 06:39
@arengarajan99 Any idea when this started happening for you? Also, could you provide more details on your LiveSplit settings (what splits/layout do you use? any autosplitters?)

**Comment by arengarajan99** [comment] 2020-06-15 06:53
This problem is recent, I don't recall when it started happening, but I know its on the current version 1.8.10 or on the previous version. I use subsplits layout with Unreal Engine loadless timer. (norm is my layout file)
[livesplit bugs.zip](https://github.com/LiveSplit/LiveSplit/files/4778474/livesplit.bugs.zip)

**Comment by wooferzfg** [comment] 2020-06-15 07:16
Could you confirm that the [User objects](https://superuser.com/a/1206362) for LiveSplit in your Task Manager are constantly going up? If that's the case, it would be helpful if you could try to determine the earliest LiveSplit version that still has this issue.
