### ISSUE TITLE
PB Segments (Possible Bug, Otherwise Feature Request)

### ISSUE THREAD

**Issue by RickardNi** [LiveSplit/LiveSplit#769] opened 2017-05-29 17:17 UTC
Hello!

One thing that I have not been able to produce is the possibility to show the PB for a segment in a column for my splits. It sounds simple enough, and there is an option for it, but no matter what I try, I cannot reproduce my wanted behaviour. What I want is the column to show me the PB for that segment (often called Golden Segment). Period.

I have an example here:
[https://www.youtube.com/watch?v=QIVwNiDls0g](https://www.youtube.com/watch?v=QIVwNiDls0g)

Starting the run, it really shows all the best times for each and every segment.

Going to 6:13 (video time), we can see that setting a new PB for that segment updates the column correctly. Great! Same thing with next segment at 11:24.

But the next segment is not a golden one. The PB column for "2. Desert Palace" shows 6:44 as best time, but at 18:12 in the video, when I split my segment, it shows 6:47 instead.

And I know, it shows me the PB for the current run, but I don't understand why. The setting is made to show me _Segment Time_ and _Best Segments_. There are already options for _Current Comparison_, _Personal Best_ (which btw, don't produce the behaviour I want), and _Avergage Segments_.

I have tried all settings that are available, and I'm not sure what the setting _Best Segments_ should do, if not show the very best segment times there is.

This might be a bug, or it is intentional behaviour. If the latter is true, I would like to make a feature request with a new Comparison type called _Golden Segements_ that does what I want.

Thank you!

**Comment by wooferzfg** [comment] 2017-05-29 21:47
This is sort of a duplicate of https://github.com/LiveSplit/LiveSplit/issues/750, but with Segment Time instead of Split Time

**Closed by wooferzfg** 2017-05-29 21:47 UTC
