### ISSUE TITLE
Margin of Error for Best Segments

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#587] opened 2016-08-20 20:49 UTC
Not every game is able to use an auto-splitter, and those with inconsistent load times makes knowing the time without loading difficult at times. Sometimes you can best a segment in real time but not when you exclude the loading. If there was a way to have a 'margin of error', you'll know if it's possible that you beat the time w/o loads too. Perhaps using a silver split color to indicate it would work.

Example: If I have a real time best segment of 1:50.0 and w/o loads of 1:37.3, a margin of error of 0:04.5, and I get a 1:51.1, I should know to check the video if I still beat the time w/o loads. If I got a 1:58.0, I wouldn't bother.

This also applies for in-game time that's inconsistent as well. It could be added the UI by clicking the 'Other...' button in the Splits Editor to add a 'Margin of Error' tab.

**Comment by wooferzfg** [comment] 2024-04-23 02:59
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/299

**Closed by wooferzfg** 2024-04-23 02:59 UTC
