### ISSUE TITLE
splitting/pausing

### ISSUE THREAD

**Issue by Bottomfragger69** [LiveSplit/LiveSplit#2270] opened 2022-10-01 22:20 UTC
on older version of livesplit i could use the side buttons to pause and split. I updated it to version 1.8.21 today and started a run, tried to pause and timer went on. I tought that maby it just reset my key binding, went on settings and saw *none* on split and pause because i used the two side buttons to pause and split. I could not set them again when i tried to bind new keys. 
Please return this option for us that liked to be able to just split with their resting tumb on the mouse.

**Comment by comfii** [comment] 2022-10-03 15:52
do u got a tkl/100%? bind it to one of the buttons on there

**Comment by Bottomfragger69** [comment] 2022-10-03 19:18
I was thinking about the side keys on my mouse. I have used the two side buttons to pause and split for over a year. But the new update does not allow me to.

**Comment by just-ero** [comment] 2024-04-18 10:57
Is this an issue with being unable to set the buttons as your hotkeys in the settings? It's entirely possible your hotkeys were reset when you updated, so you would need to set them again.

**Comment by just-ero** [comment] 2024-04-19 09:49
Closing as duplicate of #1977.

**Closed** 2024-04-19 09:50 UTC
Labels: duplicate
