### ISSUE TITLE
Side mouse buttons do not work when setting up start-split

### ISSUE THREAD

**Issue by Yakivts** [LiveSplit/LiveSplit#2251] opened 2022-06-08 06:28 UTC
Good afternoon, I found a problem, you can not assign the side buttons of the mouse, and previously you could do it. Help me solve this problem thank you!

**Comment by LimeShep** [comment] 2022-06-13 15:10
Me too, also using older version like 1.8.15 helps but it has a new update button what i dont know how to disable WITHOUT installing new update

**Comment by BrainStone** [comment] 2023-03-11 07:14
Having the same issue.

**Comment by william98r** [comment] 2023-06-04 20:53
Same

**Comment by just-ero** [comment] 2024-04-19 09:49
Closing as duplicate of #1977.

**Closed by just-ero** 2024-04-19 09:49 UTC
Labels: duplicate
