### ISSUE TITLE
Force specific size of the window

### ISSUE THREAD

**Issue by lordlouckster** [LiveSplit/LiveSplit#2064] opened 2021-01-02 20:32 UTC
My LiveSplit window gets stuck to the aspect ratio 239:198, and I can't narrow it, unless I zoom it extremely small.

**Comment by wooferzfg** [comment] 2021-01-02 22:05
You can set a specific size in the Layout Editor. When in Vertical mode, there's a minimum width for the layout depending on the components in it.

**Comment by just-ero** [comment] 2024-04-18 15:18
Closing as this is intended behavior.

**Closed by just-ero** 2024-04-18 15:18 UTC
