### ISSUE TITLE
Add a Comparison Time component

### ISSUE THREAD

**Issue by Zannick** [LiveSplit/LiveSplit#2378] opened 2023-12-13 06:52 UTC
I can add a World Record component that shows the current world record (plus whose it is), but there's no component to show what my own PB is? That information is saved in the splits, or we can get it from SRC. At the moment I'm manually editing a text component to add that info.

**Comment by just-ero** [comment] 2024-04-18 09:38
Duplicate of #2315.

Cc @wooferzfg

**Comment by Zannick** [comment] 2024-04-18 15:44
Hey, just to be clear, this isn't a duplicate of that issue, which appears to be about the Splits component updating the split PB during a run (I think?).

In the screenshot below, I've circled:
1. my text component where I'm manually writing my PB.
2. the segment PB that shows in the Detailed Timer component during a run.
3. The "Sum of Best" component.

This PR is about making a component in the "Information" section like "Sum of Best" but that shows the PB.

![Screenshot 2024-04-18 083813](https://github.com/LiveSplit/LiveSplit/assets/518709/1ddc7fc6-0e68-4f31-8722-875c2d9269a6)

**Comment by just-ero** [comment] 2024-04-18 15:48
I somehow misread that other issue entirely. Though it's still possible this is a duplicate.

**Comment by wooferzfg** [comment] 2024-04-23 04:02
You can already do this by adding a Splits component that only shows 1 split, and override the timing method. Not planning to create a separate component for this, since almost everyone just shows their PB via the Splits component already.

**Comment by Zannick** [comment] 2024-04-23 06:40
That's not very intuitive a usage, but if it works, then I'll be satisfied.

**Comment by just-ero** [comment] 2024-04-23 07:06
> almost everyone just shows their PB via the Splits component already

I don't think this is at all fair to say. LiveSplit does have the ability to use different comparisons and it's not uncommon for a runner to compare against world record or average splits, which obviously means they are *not* showing their PB via their splits.

I think this is a perfectly fine feature request to keep open. A more generic component that simply says a comparison's name and its time for the final split would work perfectly for this. In the settings, the user simply chooses which comparison to display (or the current one). The output could just be `Personal Best    0:00:00.00`.

**Comment by just-ero** [comment] 2024-04-24 08:08
@wooferzfg Thoughts?

**Comment by Zannick** [comment] 2024-04-24 22:51
> You can already do this by adding a Splits component that only shows 1 split, and override the timing method.

This is what that looks like, if I've understood right: 
![Screenshot 2024-04-24 154447](https://github.com/LiveSplit/LiveSplit/assets/518709/ba1b6f34-b9b8-4bd5-8461-12a9ccf5718b)

Not great. I couldn't find a way to make it say what the comparison is instead of the last split name, and I'd guess it will be highlighted when the run is ongoing, which will look odd, since that split will appear twice. (The current comparison for the main Splits component in this picture is a goal time with balanced times, so it's not the PB.) My request is a lot closer to what @just-ero said, just have a generic info component to display this, similar to the other static info components like Sum of Best.

**Comment by Kuhaku9893** [comment] 2024-04-26 12:15
@Zannick
I know you want this as an official component, but if you don't mind an unofficial component, I have already developed one that you can try if you like.
https://soushinsoujin989.blogspot.com/2021/08/livesplit_76.html#ComparisonTime

@wooferzfg @just-ero
If you think this feature should be provided as an official component, I will open the source code and you can use it as you like.
(Translated by DeepL)

**Comment by wooferzfg** [comment] 2024-04-26 12:35
> If you think this feature should be provided as an official component, I will open the source code and you can use it as you like.

That would be very helpful

**Comment by Kuhaku9893** [comment] 2024-04-26 13:28
The source code has been uploaded to GitHub. Please feel free to use it.
https://github.com/Kuhaku9893/LiveSplit.ComparisonTime
- The project files are not in SDK style.
- UpdateURL in ComponentFactory.cs is currently blank.
- RunPrediction source code is used.

(Translated by DeepL)

**Closed** 2024-04-28 16:18 UTC
Labels: enhancement
