### ISSUE TITLE
Add Settings to ASLs

### ISSUE THREAD

**Issue by drtchops** [LiveSplit/LiveSplit#373] opened 2015-08-17 01:25 UTC
It would be nice if we could specify settings for ASL scripts. People may not want to enable autosplits, or certain splits, or autoreset.

One simple solution is to add the same Split, Start, and Reset options to all ASLs. This will enable or disable the corresponding actions in the ASL. It might be nice to hide the option if that action is not defined in the ASL.

A more complicated option would be to allow the ASL to define what options it has and auto-generate a form for these options. This would allow you to do more complicated things like change which splits activate.

**Comment by Dread2472** [comment] 2015-08-17 20:29
This would be super useful, as right now adding autosplitters to old games is almost impossible unless they are like level changes or something. This would also keep us from having to have multiple versions of scripts floating around combined with the new multiple game version scripts.

**Comment by tduva** [comment] 2016-01-14 20:50
Some sort of Checkboxes that can be created and accessed out of an ASL script to enable/disable certain splits or features would be extremely useful.

**Comment by tduva** [comment] 2016-01-17 17:08
Is anyone already working on this? I never made a LiveSplit component (or even worked with C#) so I don't really have the overview how stuff works together.

I'm thinking a relatively simple way of implementing custom settings would be like this:
* The script author can define a list of boolean settings in the `init { }` function. This could be attached to the vars-variable or a dedicated `settings` one similiar to `refreshRate`.
  * I'm not sure what a fitting data structure would be here. There would at least have to be a string/boolean to define the setting name and default value, but separating name/label would probably be better in case the script author wants to change the label but not the setting name.
  * There could also be a separate `settings { }` function that gets executed before `init { }` if the settings are supposed to be already usable in `init { }`, but I think it's most important to have them in the other functions that actually affect the timer.
* On script initialization, the component would populate a CheckedListBox with the defined settings, read the setting values from file if already present (as I understand they are stored in the splits file) and also give the values back to the script via the `settings` variable.
* Everytime the user changes the state of one of the boolean values in the GUI, it updates the values in the script accordingly.
* The communication with the ASLScript could be done through the [UpdateScript()](https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/master/Component.cs#L77) function, since that has access to both the current ASLScript and the ComponentSettings. Setting changes could either be pulled or detected by the GUI and some flag changed or something.

Not quite a perfect solution, but if it works it would allow for things like which sections are going to be split to be changed by the user.

Would anyone be willing to implement this or to accept a Pull Request if I manage to learn how to do it? I think this would really improve the usefulness of ASL scripts.

**Comment by fatalis** [comment] 2016-01-18 00:52
Sounds good to me. I don't think anyone else would work on this anytime soon so if you could get it done that would be great. If everything works properly I'm sure it'd get merged.

**Comment by tduva** [comment] 2016-01-18 17:39
A bit of a problem I noticed is that if the settings are defined in `init { }`, it would only add the settings to the GUI if the game is actually running, which of course won't always be the case. I can think of two ways to do this:

* Run a `settings { }` ASLMethod directly after parsing the script.
  * This allows for dynamic creation of settings if necessary. For example if the script already defines some data structure that contains split names and addresses to check, settings could be created automatically from that.
  * The problem is that the current ASLMethod depends on the process being already opened, so that would have to be rewritten/a new ASLMethod added. The scripter also has to be aware that this method is different from the other ones and doesn't allow access to the same stuff.
* Define a `settings { }` section similiar to the `state { }` section where settings are defined in a custom format and parsed and given to the ASLScript during parsing of the script.
  * This means there is no confusion over what this is and it's easy to add for scripters, but it doesn't allow for dynamic creation of settings.
  * This would require a change of the ASLGrammar and ASLParser.

I'm not quite sure which solution is better. Both require changes I'm not really comfortable with, but it appears it has to be done.

**Comment by fatalis** [comment] 2016-01-18 18:07
We kind of need a generic "script startup" method already, so maybe you could tie that in. If you end up doing that, a shutdown method should be added as well. You should just do whatever, since the language is already a hacky mess that needs to be rewritten (partly my fault lol).

**Comment by tduva** [comment] 2016-01-18 18:22
I'm sure it's going to get better when it's edited by someone who doesn't even know C#. :P

**Comment by tduva** [comment] 2016-01-22 01:53
I've been working on this and was wondering a few things.

* The settings are added from the ASLScript in a pre-init method and stored as ALSSetting objects. Those objects are used to check the state of the setting (on/off) in the ASLScript as well as passed to the GUI where they are displayed in a CheckedListBox. Checking/unchecking the items in the list also changes the boolean value in the ASLSetting object. I'm not quite sure how threads work in this, would changing the value in the object from the GUI cause issues in the script (which I assume runs in a different thread from the GUI)?
* I added a new ASL script method that is executed right after parsing the script (and before the game is connected). This is where settings have to be added, but also other stuff could be defined that doesn't depend on the game yet. Any name suggestions?
* Is there a way I can automatically adjust the size of the ComponentSettings to the size of the settings dialog it is embedded in? When I resize the form it changes the elements in it accordingly, but I'm not sure how to autosize the form itself.

**Comment by fatalis** [comment] 2016-01-22 22:27
* ASL script methods are called on the UI thread.
* "startup" / "shutdown" ?
* https://msdn.microsoft.com/en-us/library/system.windows.forms.control.dock%28v=vs.110%29.aspx

**Comment by tduva** [comment] 2016-01-23 22:17
Thanks. Shouldn't cause any problems then other that it might be a bit messy.

What would a shutdown method be used for? When would it even be executed exactly?

The Dock-property wasn't there in the designer for the UserControl component and when I added it manually, it became way too big and added scrollbars. For now I'll just keep it at a reasonable width/height.

I was also pondering if adding split/start/reset checkboxes in addition to the custom ones would also make sense. Script developers could easily add those manually via custom settings as well, but it might be convenient to just have them by default for all scripts. If so, then the question is also what e.g. disabling "split" exactly does:

* It prevents the split-method from being executed
* It still executes the split-method, but prevents the split-method from splitting

This could make a difference if the script does someting in the split-method that affects the other (maybe still enabled) methods. Not entirely sure what that could be, but script developers may rely on the method being executed. Not sure if they should do that, but something to consider at least.

Also, does disabling gametime/load removal make sense? If you don't want that, couldn't you just not display the game time? Or would there be other cases where it could matter. Can gametime/load removal conflict with eachother?

**Comment by fatalis** [comment] 2016-01-23 22:58
Shutdown would basically act as a Dispose method, where they can clean up unmanaged resources and such.

You should make the default options only show up if they're defined in the script.

It probably shouldn't stop the method from being called, since some older scripts use `start` to initialize variables. So just make it ignore the return value as you said.

Disabling game time doesn't make sense, yeah. You could have a default setting that automatically switches real time / game time comparison, because a lot of people don't know where to do that at. I don't think they can conflict.

**Comment by tduva** [comment] 2016-01-28 10:16
Can you give an example for what you would need to cleanup in an ASL script? Either way, I added a shutdown medthod as well.

This is what I've added so far: [Diff](https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/compare/master...tduva:asl-settings)

I also changed the initialization a bit, moved it in it's own method which is run until it ran without errors. Since `init` can be run more than once anyway (game restart), this shouldn't cause any additional issues (besides it mostly will fail before `init` even runs, when updating the state values).

I also added checkboxes for start/split/reset.

I don't think I mentioned that yet, I also added a label with the value from `version` to the GUI. I'm not entirely sure if that fits in there (it's not really a setting), but I think it could be a useful information for some games that have different versions and maybe provide some features only for some versions or something. There isn't really any other good way to provide feedback to the user of the script. If no `version` is set, the label is invisible.

Related to the `version` variable, I was also wondering if it's on purpose that even if it's set in `init` the value is only visible in the other ASL methods if there is a matching state descriptor (which causes it to keep using the default state descriptor). I feel like if you set that variable as a script author, you might expect it to stay set either way (even though it could indicate whether there is a state descriptor for that version or not, but the script author should probably know that anyway). But I might have misunderstood something there.

Example screenshot of the current state:
![asl_settings2](https://cloud.githubusercontent.com/assets/5621113/12641535/5458b4fa-c5b0-11e5-9478-fd3b7e052f94.jpg)

**Comment by fatalis** [comment] 2016-01-29 02:00
>Can you give an example for what you would need to cleanup in an ASL script?

I can't think of a real world example off the top of my head right now but I'm sure it won't be useless.

>Related to the version variable...

Sounds like an oversight, yeah. It'd be better to change it to do that.

Make sure the settings dialog works in the splits editor when you click Settings, not just in the layout editor.

**Comment by tduva** [comment] 2016-01-29 03:46
You probably already know what I mean, but just to clarify because I wrote parts of it a bit weird (and making an additional point).

* When you set `version` in `init` *with* a matching state descriptor, it uses that state descriptor instead of the default one and `version` is set, as expected.
* When you set `version` in `init` *without* a matching state descriptor, it's as if you never set it at all:
  * The default state descriptor keeps being used, instead of not using any at all, which I would have expected from reading the documentation. Either way could make sense, but I would be hesitant to change it anyway, because it might break existing scripts.
  * The `version` variable doesn't get set, which as I already explained seems a bit weird. If I understood your response correctly you agree that changing that to always be set (regardless of a matching state descriptor being there or not) makes sense. That change might also break existing scripts, but it might be less of a problem (not sure if I ever saw a script that relies on `version` being empty just because of a missing state descriptor despite being explicitly set by the script author).

Is there any reason it would work differently in the Splits Editor compared to the Layout Settings? I already adjusted the height a bit because apparently the settings window in the Splits Editor is a bit less tall. From what I tested it seems to work fine.

Another thing I was thinking about is, how would the transition take place from old to new scripts. Old existing scripts should still work fine, but if new scripts start using the settings older versions of LiveSplit wouldn't be able to load them anymore. Are people just expected to update? Will the current version ignore entries from the `LiveSplit.AutoSplitters.xml` that have an unknown type or just fail to load it completely? From glancing at the code I would expect it to be the latter, but I'm not quite sure.

**Comment by fatalis** [comment] 2016-01-29 20:43
I haven't seen a single script that runs with a "no-matching-descriptor" version, so you could probably change that without breaking anything. (and the other thing)

>Are people just expected to update?

Yeah, I think so, some stuff in LS already works like that IIRC.

>Will the current version ignore entries from the LiveSplit.AutoSplitters.xml that have an unknown type or just fail to load it completely? 

It'll ignore them, see how I implemented <Website> a while back.

**Comment by tduva** [comment] 2016-01-30 02:59
I'm not even sure which way is better though. It's a decision between:

* Scripts that want to set a `version` to prevent the script from executing at all for unknown/unsupported versions having to use `if (version == "")` or whatever in `start`, `split`, `reset` and so on to prevent execution of those methods manually.
* Scripts that want to set a `version` for use in the methods (or to display it in the settings), but don't need a state descriptor for it, having to add empty state descriptors.

Both ways have their merits and would work if it's clarified in the documentation.

**Comment by tduva** [comment] 2016-02-03 09:04
I can't really decide which way is better, so I'll leave it as it is (except for `version` being always set of course).

I had an idea about how to make it easier to disable the script for unsupported versions though. If you return false in `update` it could just not run any of the other methods as well. That way there could be a `if (version == "") { return false; }` in just `update` instead of `start`, `split`, `reset` and whatnot. I looked through most of the ASL scripts in the XML and none seem to return false in `update` yet, so it hopefully shouldn't break any existing scripts.

I also followed the comment in the ASLScript class and changed it so that when connecting to the game always the state descriptor without a version defined is selected by default, unless there is none, then the first one is selected as before.

I was wondering why the Component writes Version/1.4 to the settings XML. What is that used for? In the Factory.cs the version is 1.6.3. Is that the Component version or the LiveSplit version the Component was made for?

**Comment by fatalis** [comment] 2016-02-03 12:35
>If you return false in update it could just not run any of the other methods as well.

+1

>I was wondering why the Component writes Version/1.4 to the settings XML.

I think it's just a semi-arbitrary string used for versioning. I guess the number wasn't bumped because of laziness and nothing changed. [here](https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/92e4f3c14f25c93bfd26f7af8469be70bf529a83/ComponentSettings.cs#L23)

Can you show what settings declaration looks like? I assume it lets you define a default value?

**Comment by tduva** [comment] 2016-02-03 13:36
In the `startup` method you can add settings like this (with `true` being the default value set to enabled):

    AddSetting("settingId", true, "description/label shown in the GUI");

And in the other methods (except `shutdown`) you can check if the setting is enabled:

    if (Enabled("settingId")) { }

This is realized by [providing an Action/Func to the ASL script environment](https://github.com/tduva/LiveSplit.ScriptableAutoSplit/blob/0fe5645501fcd850b73dea229699c96230a41583/ASL/ASLMethod.cs#L124). I haven't really worked with this before, so I'm not sure if this has any disadvantages (performance or something since it's called so often), but it seems to work fine.

**Comment by tduva** [comment] 2016-02-08 06:53
I did some testing and it didn't seem to make any noticeable difference in execution time where the Enabled-Func is defined.

**Closed** 2017-06-03 01:39 UTC
Labels: Enhancement
