### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by matej118111** [LiveSplit/LiveSplit#2252] opened 2022-06-11 19:00 UTC
This is common issue with alot of software, i don't want to use wine just to run this

**Comment by CryZe** [comment] 2022-06-11 19:21
This is a duplicate of probably many issues as this point. We are working on a Linux version.

**Closed by CryZe** 2022-06-11 19:21 UTC

**Comment by CryZe** [comment] 2025-06-16 18:14
There is a Tauri version of LiveSplit One, there is a Druid version, an OBS plugin and a Dioxus version that I'm currently working on. They all work on Linux. Also you can run the original LiveSplit through Wine.
