### ISSUE TITLE
[Enhancement] Idea for Subsplit Icons

### ISSUE THREAD

**Issue by Derpspace** [LiveSplit/LiveSplit#1946] opened 2020-07-19 23:43 UTC
I'm Thinking you could have a separate icon for the last split of a subsplit and the header/what you see when the contents of the subsplit is not viewable.

In the photo the black square is a custom image
![Annotation 2020-07-19 183744](https://user-images.githubusercontent.com/59072461/87888030-b472a380-c9ef-11ea-8f45-36bd14502bae.png)

**Comment by wooferzfg** [comment] 2020-08-11 07:37
Duplicate of #1976

**Closed by wooferzfg** 2020-08-11 07:37 UTC
