### ISSUE TITLE
Add caching for the Speedrun.com games list

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#2473] opened 2024-04-20 08:25 UTC
The Speedrun.com games list is currently pulled:
- If no game is selected, when the Splits Editor is opened.
- If a game is selected, when LiveSplit starts.

There's about 40,000 games now, so pulling every game requires 40 API calls. Instead of making these API calls so often, it would be nice to cache the games list in most cases, and maybe invalidate it when it gets stale enough (a decision needs to be made on how to handle this part).

**Comment by just-ero** [comment] 2024-04-20 08:50
Duplicate of #504.

**Closed** 2024-04-20 18:50 UTC
Labels: enhancement
