### ISSUE TITLE
Error Creating Window Handle

### ISSUE THREAD

**Issue by BlueLovin** [LiveSplit/LiveSplit#2185] opened 2021-11-14 00:40 UTC
I've seen a lot of people having this issue. It is really frustrating having to open livesplit over and over and over again during a speedrun sesh. It always crashes after i hit a hotkey (that doesnt work), then right clicking on livesplit. This is most likely due to some new .net update that has been installed to our Windows machines. 

pls fix :)

![image](https://user-images.githubusercontent.com/9152257/141663238-9fe8d8e6-8347-416e-9555-badcf6888be6.png)

**Comment by wooferzfg** [comment] 2021-11-14 00:59
Could you try disabling "Allow Gamepads as Hotkeys" in the settings?

**Comment by BlueLovin** [comment] 2021-11-18 15:53
> 
> 
> Could you try disabling "Allow Gamepads as Hotkeys" in the settings?

seemed to have resolved the crashing issue, thank you.

**Comment by BlueLovin** [comment] 2021-12-01 04:54
> Could you try disabling "Allow Gamepads as Hotkeys" in the settings?

Still getting intermittent crashes the more I use it... Same error.

**Comment by BlueLovin** [comment] 2021-12-08 14:59
> Do you have DS4Windows installed?

negative :(

**Comment by BlueLovin** [comment] 2022-01-20 01:05
i'm really really really sick of this issue. i can not close Livesplit at all anymore without it throwing this error. :\

**Comment by CryZe** [comment] 2022-01-20 01:34
In the Task Manager, go to the details tab, right click on the columns, and activate User handles / objects (I forgot what the exact name is in english) and see how it behaves. Also try disabling the "Allow Gamepads as Hotkeys" setting and then make sure to restart LiveSplit (it doesn't seem to affect the problem until you restart).

**Comment by SuperSajuuk** [comment] 2023-10-01 19:46
Hey @BlueLovin I'm not sure if you still use the app or not, but I got linked this thread in one of my own reporting the same issue. What you're seeing is a crash due to an inconsistent memory leak of user objects [which is limited to 10,000], which you can monitor using the Windows Task Manager and showing the column for user objects in the details tab. Once the app hits 10k, then any opening of the right-click context menu [or indeed taking any action in the app that excludes hotkeys] will crash the app.

The only fix I've seen for this is to have Task Manager open, and then close and reopen LiveSplit over and over (after waiting 10-15 seconds before closing the app in each attempt, so that you can monitor the critical stats) until the User Objects count stays around 60-70 in the idle state. You can also check Threads, Handles and GDI Objects similarly via TM to ensure these are not mem leaking.

**Comment by wooferzfg** [comment] 2024-04-21 01:34
Duplicate of #1867

**Closed by wooferzfg** 2024-04-21 01:34 UTC
Labels: bug
