### ISSUE TITLE
Feature Request: Allow for subsplits to not count in the sum of best.

### ISSUE THREAD

**Issue by bbohls** [LiveSplit/LiveSplit#1300] opened 2019-03-06 02:32 UTC
Currently a subsplit will update the sum of best. Can there be a way that you can select the segments that count toward the sum of best, or have an option to not count subsplits toward the sum of best.

**Comment by chillex0** [comment] 2019-07-06 23:37
That can be done using MS Excel; you can group segments together and find your sum of best "groups".

**Comment by metoxys** [comment] 2019-10-26 20:42
Seconding this request, I use livesplit a lot for (motorsports) racing and having every single checkpoint count as a split can produce highly unrealistic "best" times

**Comment by alexozer** [comment] 2019-11-27 14:31
Thirding this request. Letting subsplits to not count towards SOB would allow runners (myself included) to more carefully monitor smaller segments of their runs, while keeping a realistic SOB that's consistent with the metric of other runners of the same category.

One simple implementation might be to just add a checkbox to the "Sum of Best" widget settings like "Count Subsplits Towards Sum-of-Best". If finer control was desired (say to count only some subsplits but not others), maybe a small optional syntax for marking which subsplits should be counted could be added to the subsplit naming syntax.

**Comment by metoxys** [comment] 2019-11-27 15:57
> One simple implementation might be to just add a checkbox to the "Sum of Best" widget settings like "Count Subsplits Towards Sum-of-Best". If finer control was desired (say to count only some subsplits but not others), maybe a small optional syntax for marking which subsplits should be counted could be added to the subsplit naming syntax.

Seconding this

**Comment by exertoins** [comment] 2021-02-12 13:03
Would also really like this. Sum of best is not accurate when it counts subsplits.

**Comment by TheTaraStark** [comment] 2024-01-18 15:45
This looks like a dupe of #122 if I'm not mistaken, can they be merged/closed?

**Comment by just-ero** [comment] 2024-04-18 18:12
Closing as duplicate.

**Closed by just-ero** 2024-04-18 18:12 UTC
Labels: Duplicate
