### ISSUE TITLE
Crashes everytime, Error creating window handle.

### ISSUE THREAD

**Issue by SlenderXIV** [LiveSplit/LiveSplit#2165] opened 2021-09-04 22:28 UTC
Constantly crashes within 2 minutes of using it no matter what I try to do, someone said that downgrading to 1.8.15 fixes this specific error but it didn't work for me.
Here is a plain text copy of the 2 event logs for 1.8.16:

Log Name:      Application
Source:        LiveSplit
Date:          05/09/2021 00:12:25
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-K4CU4MC
Description:
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-04T22:12:25.6277644Z" />
    <EventRecordID>38566</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-K4CU4MC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG&amp; msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        LiveSplit
Date:          05/09/2021 00:12:25
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-K4CU4MC
Description:
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at LiveSplit.View.TimerForm.WndProc(Message& m)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-04T22:12:25.5227649Z" />
    <EventRecordID>38565</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-K4CU4MC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message&amp; m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message&amp; m)
   at System.Windows.Forms.Form.WndProc(Message&amp; m)
   at LiveSplit.View.TimerForm.WndProc(Message&amp; m)</Data>
  </EventData>
</Event>

**Comment by BlueLovin** [comment] 2021-10-30 16:39
Likely to do with a .NET windows update we installed. This issue is happening to me too, even some of my hotkeys aren't working anymore.

**Comment by wooferzfg** [comment] 2021-12-08 14:58
Do you have DS4Windows installed?

**Comment by lukhuber** [comment] 2021-12-10 19:33
I have the same error and happened to install DS4Windows today. Never had this issue before. Literally started when installing DS4Windows + associated .NET version. Nothing else was changed on the system

**Comment by lukhuber** [comment] 2021-12-10 22:08
Disabling "Allow Gamepads as Hotkeys" seems to fix the issue.

**Comment by BlueLovin** [comment] 2021-12-10 22:09
Disabling that option did not fix it for me sadly.

**Comment by v3stige** [comment] 2021-12-21 23:40
I also started having this error. I also have ds4windows installed on my computer. I tried disabling the allow gamepads as hotkeys option as well but it didn't seem to have any effect.

**Comment by BentzStream** [comment] 2021-12-29 02:57
If anyone has a fix please let me know I'm having all of the same problems

**Comment by wooferzfg** [comment] 2024-04-23 03:22
Duplicate of #1867

**Closed by wooferzfg** 2024-04-23 03:22 UTC
